### ISSUE TITLE
New API and sugar

### ISSUE THREAD

**Issue by buschtoens** [buschtoens/sanitize-arguments#10]
How should the new API be structured? Which new functionalities should be added?
#4 method overloading is a good idea, since this is what we basically try to do. But maybe this could be passed by, if we just add enough sugar. I don't like redefining methods and wrapper functions.

The proposed API is as follows:

``` javascript
sanitize(arguments, [caller,] [ String, Number, [ Boolean, true ], String ]);
```

The array can now hold types and arrays which contain the type and default value.

If `caller` is supplied `sanitize` will return an object with the expected arguments as keys, instead of a plain array.

If we want to opt-in for the JavaScript magic that will be obsolete in ES6 (or `"use strict";`), we could completely omit `arguments` and `caller`, and could use the magic link of `arguments`. Contra: The link only works correctly if _all/enough_ arguments have been supplied, which is most often not the case.

**Comment by buschtoens** [comment]
Idea:

``` javascript
sanitize(arguments, [caller,] [ String, Number, true, String ]);
```

Why explicitely define the type, although it's implied by the value itself? Looks way more expressive and clean than the above?

Are there any downsides?

**Comment by jbrumwell** [comment]
I like the syntax it does make it a little simplier, something like this might give it a good start, I'm not at my computer though so many errors inside lol

``` javascript
order.some(function(type, newIndex) {
        var name;

        if( typeOf(type) == 'Function') {
                name = type.name;

                if (typeOf(arg) == 'Function' && ['String', 'Boolean', 'Function', 'Number', 'Date', 'Float', etc].indexOf(name) == -1) {
                    yes = true;
                }  else if (nameOf(arg) == typeOf(type)) {
                    yes = true;
                }          
        } else if (typeOf(arg) == typeof(type)) {
                yes = true;
        }

        if (yes) {
                args[newIndex] = arg;
        if(caller) sanitized[argNames[newIndex]] = arg;
        delete order[newIndex];
        return true;            
        }
});
```

I also think it would be good to support detecting objects that are an instnaceof functions.

In the current implementation it might look like this;

``` javascript
order.some(function(type, newIndex) {
                        var _type = typeOf(type) == "Array" ? type[0] : type;

            if(typeOf(_type) == "Function" && (typeOf(arg) == nameOf(_type) || arg instanceof nameOf(type) )) {
                args[newIndex] = arg;
                if(caller) sanitized[argNames[newIndex]] = arg;
                delete order[newIndex];
                return true;
            }
        });
```

This would allow something liike

`sanitize(arguments, Caller, [String, Person]);`

When called like so;

`Caller('John Doe', new Person());`

**Comment by buschtoens** [comment]
Looks Good, will try out later. I'm currently not at home either.

But AFAIK the `instanceof` part is unnecessary, because `typeOf(obj)`
takes care of this. That's why I implemented this function at all; I
was I unsatisfied with the weird behavior of `typeof` and
`instanceof`.

**Comment by jbrumwell** [comment]
Good to hear, the above code snippet won't work out of the box. Are there any internal types that I missed? If you remove the "etc" variable in the internal function check it may run not sure about bugs though.

**Comment by buschtoens** [comment]
Well, JS has no `Float`, it's simply `Number`. But you are missing `RegExp`.
I don't like this check for primitive types only. What if someone wants to pass a `Person`?

The only problem I see are default functions. I guess we'll have to double check and assume it's a function (and not a class) if it is an anonymous function. Named functions shall always be classes. We'll have to note that in the docs.

**Comment by jbrumwell** [comment]
I agree and I think this change might actually be a step backwards, and limit adoption. It introduces some unexpected behaviour. What do you think?

I'd actually prefer sticking with the nested arrays in this case.

**Comment by buschtoens** [comment]
Yup, it would have been really sweet sugar, but the risk of getting unexpected behaviour is just too big.

But there's a way to explicitly mark the input as defaults. We can wrap them, just like your original proposal.

``` javascript
// 1 (yours)
sanitize(arguments, [caller,] [ String, Number, [ Boolean, true ], [ Function, function () {} ]);

// 2 (yours shortened, the type is optional)
sanitize(arguments, [caller,] [ String, Number, [ true ], [ function () {} ]);
```

I'd prefer _2_. It can be combined with _1_. Defaults are plain to see, everything looks quite expressive and we don't have the hassle with function and class ambiguity.  
Nonetheless the type attribute in `[ type, default ]` should only be optional, and not completely removed, so one could do things like `[ String, false ]`.

**Comment by jbrumwell** [comment]
In your implementation;

`if (type.length == 1) _type = typeOf(type[0]);`

is always going to equal a string and never pass the next condition

`if(typeOf(_type) == "Function" && typeOf(arg) == nameOf(_type)) {`

**Comment by buschtoens** [comment]
Whups... My bad. I'll be back at a computer in 30 minutes? Or do you wanna PR?

**Comment by jbrumwell** [comment]
Yes will send one in a couple minutes

**Comment by buschtoens** [comment]
Thanks.

**Comment by jbrumwell** [comment]
no problem!

**Comment by jbrumwell** [comment]
Just got to figure out how to rebase my fork, think I found it though

**Comment by buschtoens** [comment]
#12
